create table rsvp (
  id bigint generated by default as identity primary key,
  name text not null,
  attendance text not null,
  message text,
  created_at timestamptz default now()
);

alter table rsvp enable row level security;

create policy "Allow public insert RSVP"
on rsvp
for insert
to anon
with check (true);

create policy "Allow public read RSVP"
on rsvp
for select
to anon
using (true);